// Generated by gencpp from file visp_hand2eye_calibration/getposesResult.msg
// DO NOT EDIT!


#ifndef VISP_HAND2EYE_CALIBRATION_MESSAGE_GETPOSESRESULT_H
#define VISP_HAND2EYE_CALIBRATION_MESSAGE_GETPOSESRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseStamped.h>
#include <geometry_msgs/PoseStamped.h>

namespace visp_hand2eye_calibration
{
template <class ContainerAllocator>
struct getposesResult_
{
  typedef getposesResult_<ContainerAllocator> Type;

  getposesResult_()
    : camera_object_pose()
    , ee_pose()  {
    }
  getposesResult_(const ContainerAllocator& _alloc)
    : camera_object_pose(_alloc)
    , ee_pose(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _camera_object_pose_type;
  _camera_object_pose_type camera_object_pose;

   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _ee_pose_type;
  _ee_pose_type ee_pose;





  typedef boost::shared_ptr< ::visp_hand2eye_calibration::getposesResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::visp_hand2eye_calibration::getposesResult_<ContainerAllocator> const> ConstPtr;

}; // struct getposesResult_

typedef ::visp_hand2eye_calibration::getposesResult_<std::allocator<void> > getposesResult;

typedef boost::shared_ptr< ::visp_hand2eye_calibration::getposesResult > getposesResultPtr;
typedef boost::shared_ptr< ::visp_hand2eye_calibration::getposesResult const> getposesResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::visp_hand2eye_calibration::getposesResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::visp_hand2eye_calibration::getposesResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace visp_hand2eye_calibration

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'visp_hand2eye_calibration': ['/home/srinath/catkin_thesis/src/hand_eye_calib/visp_hand2eye_calibration/msg', '/home/srinath/catkin_thesis/devel/share/visp_hand2eye_calibration/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::visp_hand2eye_calibration::getposesResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::visp_hand2eye_calibration::getposesResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::visp_hand2eye_calibration::getposesResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::visp_hand2eye_calibration::getposesResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::visp_hand2eye_calibration::getposesResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::visp_hand2eye_calibration::getposesResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::visp_hand2eye_calibration::getposesResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "df7ebed0c741ba5d6ab303f0b00df9ec";
  }

  static const char* value(const ::visp_hand2eye_calibration::getposesResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdf7ebed0c741ba5dULL;
  static const uint64_t static_value2 = 0x6ab303f0b00df9ecULL;
};

template<class ContainerAllocator>
struct DataType< ::visp_hand2eye_calibration::getposesResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "visp_hand2eye_calibration/getposesResult";
  }

  static const char* value(const ::visp_hand2eye_calibration::getposesResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::visp_hand2eye_calibration::getposesResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# Define the result\n\
geometry_msgs/PoseStamped camera_object_pose\n\
geometry_msgs/PoseStamped ee_pose\n\
\n\
================================================================================\n\
MSG: geometry_msgs/PoseStamped\n\
# A Pose with reference coordinate frame and timestamp\n\
Header header\n\
Pose pose\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of position and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::visp_hand2eye_calibration::getposesResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::visp_hand2eye_calibration::getposesResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.camera_object_pose);
      stream.next(m.ee_pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct getposesResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::visp_hand2eye_calibration::getposesResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::visp_hand2eye_calibration::getposesResult_<ContainerAllocator>& v)
  {
    s << indent << "camera_object_pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.camera_object_pose);
    s << indent << "ee_pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.ee_pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VISP_HAND2EYE_CALIBRATION_MESSAGE_GETPOSESRESULT_H
