// Generated by gencpp from file visp_hand2eye_calibration/getposesFeedback.msg
// DO NOT EDIT!


#ifndef VISP_HAND2EYE_CALIBRATION_MESSAGE_GETPOSESFEEDBACK_H
#define VISP_HAND2EYE_CALIBRATION_MESSAGE_GETPOSESFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace visp_hand2eye_calibration
{
template <class ContainerAllocator>
struct getposesFeedback_
{
  typedef getposesFeedback_<ContainerAllocator> Type;

  getposesFeedback_()
    : poses_sent(false)  {
    }
  getposesFeedback_(const ContainerAllocator& _alloc)
    : poses_sent(false)  {
  (void)_alloc;
    }



   typedef uint8_t _poses_sent_type;
  _poses_sent_type poses_sent;





  typedef boost::shared_ptr< ::visp_hand2eye_calibration::getposesFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::visp_hand2eye_calibration::getposesFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct getposesFeedback_

typedef ::visp_hand2eye_calibration::getposesFeedback_<std::allocator<void> > getposesFeedback;

typedef boost::shared_ptr< ::visp_hand2eye_calibration::getposesFeedback > getposesFeedbackPtr;
typedef boost::shared_ptr< ::visp_hand2eye_calibration::getposesFeedback const> getposesFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::visp_hand2eye_calibration::getposesFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::visp_hand2eye_calibration::getposesFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace visp_hand2eye_calibration

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'visp_hand2eye_calibration': ['/home/srinath/catkin_thesis/src/hand_eye_calib/visp_hand2eye_calibration/msg', '/home/srinath/catkin_thesis/devel/share/visp_hand2eye_calibration/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::visp_hand2eye_calibration::getposesFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::visp_hand2eye_calibration::getposesFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::visp_hand2eye_calibration::getposesFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::visp_hand2eye_calibration::getposesFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::visp_hand2eye_calibration::getposesFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::visp_hand2eye_calibration::getposesFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::visp_hand2eye_calibration::getposesFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f555082d98a684b739b7f9ebba06a141";
  }

  static const char* value(const ::visp_hand2eye_calibration::getposesFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf555082d98a684b7ULL;
  static const uint64_t static_value2 = 0x39b7f9ebba06a141ULL;
};

template<class ContainerAllocator>
struct DataType< ::visp_hand2eye_calibration::getposesFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "visp_hand2eye_calibration/getposesFeedback";
  }

  static const char* value(const ::visp_hand2eye_calibration::getposesFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::visp_hand2eye_calibration::getposesFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# Define a feedback message\n\
bool poses_sent\n\
";
  }

  static const char* value(const ::visp_hand2eye_calibration::getposesFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::visp_hand2eye_calibration::getposesFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.poses_sent);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct getposesFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::visp_hand2eye_calibration::getposesFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::visp_hand2eye_calibration::getposesFeedback_<ContainerAllocator>& v)
  {
    s << indent << "poses_sent: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.poses_sent);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VISP_HAND2EYE_CALIBRATION_MESSAGE_GETPOSESFEEDBACK_H
