(cl:defpackage visp_hand2eye_calibration-msg
  (:use )
  (:export
   "<TRANSFORMARRAY>"
   "TRANSFORMARRAY"
   "<GETPOSESACTION>"
   "GETPOSESACTION"
   "<GETPOSESACTIONFEEDBACK>"
   "GETPOSESACTIONFEEDBACK"
   "<GETPOSESACTIONGOAL>"
   "GETPOSESACTIONGOAL"
   "<GETPOSESACTIONRESULT>"
   "GETPOSESACTIONRESULT"
   "<GETPOSESFEEDBACK>"
   "GETPOSESFEEDBACK"
   "<GETPOSESGOAL>"
   "GETPOSESGOAL"
   "<GETPOSESRESULT>"
   "GETPOSESRESULT"
  ))

