; Auto-generated. Do not edit!


(cl:in-package visp_hand2eye_calibration-msg)


;//! \htmlinclude getposesResult.msg.html

(cl:defclass <getposesResult> (roslisp-msg-protocol:ros-message)
  ((camera_object_pose
    :reader camera_object_pose
    :initarg :camera_object_pose
    :type geometry_msgs-msg:PoseStamped
    :initform (cl:make-instance 'geometry_msgs-msg:PoseStamped))
   (ee_pose
    :reader ee_pose
    :initarg :ee_pose
    :type geometry_msgs-msg:PoseStamped
    :initform (cl:make-instance 'geometry_msgs-msg:PoseStamped)))
)

(cl:defclass getposesResult (<getposesResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <getposesResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'getposesResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name visp_hand2eye_calibration-msg:<getposesResult> is deprecated: use visp_hand2eye_calibration-msg:getposesResult instead.")))

(cl:ensure-generic-function 'camera_object_pose-val :lambda-list '(m))
(cl:defmethod camera_object_pose-val ((m <getposesResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader visp_hand2eye_calibration-msg:camera_object_pose-val is deprecated.  Use visp_hand2eye_calibration-msg:camera_object_pose instead.")
  (camera_object_pose m))

(cl:ensure-generic-function 'ee_pose-val :lambda-list '(m))
(cl:defmethod ee_pose-val ((m <getposesResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader visp_hand2eye_calibration-msg:ee_pose-val is deprecated.  Use visp_hand2eye_calibration-msg:ee_pose instead.")
  (ee_pose m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <getposesResult>) ostream)
  "Serializes a message object of type '<getposesResult>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'camera_object_pose) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'ee_pose) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <getposesResult>) istream)
  "Deserializes a message object of type '<getposesResult>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'camera_object_pose) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'ee_pose) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<getposesResult>)))
  "Returns string type for a message object of type '<getposesResult>"
  "visp_hand2eye_calibration/getposesResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'getposesResult)))
  "Returns string type for a message object of type 'getposesResult"
  "visp_hand2eye_calibration/getposesResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<getposesResult>)))
  "Returns md5sum for a message object of type '<getposesResult>"
  "df7ebed0c741ba5d6ab303f0b00df9ec")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'getposesResult)))
  "Returns md5sum for a message object of type 'getposesResult"
  "df7ebed0c741ba5d6ab303f0b00df9ec")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<getposesResult>)))
  "Returns full string definition for message of type '<getposesResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the result~%geometry_msgs/PoseStamped camera_object_pose~%geometry_msgs/PoseStamped ee_pose~%~%================================================================================~%MSG: geometry_msgs/PoseStamped~%# A Pose with reference coordinate frame and timestamp~%Header header~%Pose pose~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%# 0: no frame~%# 1: global frame~%string frame_id~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of position and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'getposesResult)))
  "Returns full string definition for message of type 'getposesResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the result~%geometry_msgs/PoseStamped camera_object_pose~%geometry_msgs/PoseStamped ee_pose~%~%================================================================================~%MSG: geometry_msgs/PoseStamped~%# A Pose with reference coordinate frame and timestamp~%Header header~%Pose pose~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%# 0: no frame~%# 1: global frame~%string frame_id~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of position and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <getposesResult>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'camera_object_pose))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'ee_pose))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <getposesResult>))
  "Converts a ROS message object to a list"
  (cl:list 'getposesResult
    (cl:cons ':camera_object_pose (camera_object_pose msg))
    (cl:cons ':ee_pose (ee_pose msg))
))
