; Auto-generated. Do not edit!


(cl:in-package visp_hand2eye_calibration-msg)


;//! \htmlinclude getposesGoal.msg.html

(cl:defclass <getposesGoal> (roslisp-msg-protocol:ros-message)
  ((target_id
    :reader target_id
    :initarg :target_id
    :type cl:fixnum
    :initform 0))
)

(cl:defclass getposesGoal (<getposesGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <getposesGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'getposesGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name visp_hand2eye_calibration-msg:<getposesGoal> is deprecated: use visp_hand2eye_calibration-msg:getposesGoal instead.")))

(cl:ensure-generic-function 'target_id-val :lambda-list '(m))
(cl:defmethod target_id-val ((m <getposesGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader visp_hand2eye_calibration-msg:target_id-val is deprecated.  Use visp_hand2eye_calibration-msg:target_id instead.")
  (target_id m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <getposesGoal>) ostream)
  "Serializes a message object of type '<getposesGoal>"
  (cl:let* ((signed (cl:slot-value msg 'target_id)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 65536) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <getposesGoal>) istream)
  "Deserializes a message object of type '<getposesGoal>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'target_id) (cl:if (cl:< unsigned 32768) unsigned (cl:- unsigned 65536))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<getposesGoal>)))
  "Returns string type for a message object of type '<getposesGoal>"
  "visp_hand2eye_calibration/getposesGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'getposesGoal)))
  "Returns string type for a message object of type 'getposesGoal"
  "visp_hand2eye_calibration/getposesGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<getposesGoal>)))
  "Returns md5sum for a message object of type '<getposesGoal>"
  "c7acdf8ed086095f4ab8108e35ca5288")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'getposesGoal)))
  "Returns md5sum for a message object of type 'getposesGoal"
  "c7acdf8ed086095f4ab8108e35ca5288")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<getposesGoal>)))
  "Returns full string definition for message of type '<getposesGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the goal~%int16 target_id~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'getposesGoal)))
  "Returns full string definition for message of type 'getposesGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the goal~%int16 target_id~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <getposesGoal>))
  (cl:+ 0
     2
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <getposesGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'getposesGoal
    (cl:cons ':target_id (target_id msg))
))
