; Auto-generated. Do not edit!


(cl:in-package visp_hand2eye_calibration-msg)


;//! \htmlinclude getposesFeedback.msg.html

(cl:defclass <getposesFeedback> (roslisp-msg-protocol:ros-message)
  ((poses_sent
    :reader poses_sent
    :initarg :poses_sent
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass getposesFeedback (<getposesFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <getposesFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'getposesFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name visp_hand2eye_calibration-msg:<getposesFeedback> is deprecated: use visp_hand2eye_calibration-msg:getposesFeedback instead.")))

(cl:ensure-generic-function 'poses_sent-val :lambda-list '(m))
(cl:defmethod poses_sent-val ((m <getposesFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader visp_hand2eye_calibration-msg:poses_sent-val is deprecated.  Use visp_hand2eye_calibration-msg:poses_sent instead.")
  (poses_sent m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <getposesFeedback>) ostream)
  "Serializes a message object of type '<getposesFeedback>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'poses_sent) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <getposesFeedback>) istream)
  "Deserializes a message object of type '<getposesFeedback>"
    (cl:setf (cl:slot-value msg 'poses_sent) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<getposesFeedback>)))
  "Returns string type for a message object of type '<getposesFeedback>"
  "visp_hand2eye_calibration/getposesFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'getposesFeedback)))
  "Returns string type for a message object of type 'getposesFeedback"
  "visp_hand2eye_calibration/getposesFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<getposesFeedback>)))
  "Returns md5sum for a message object of type '<getposesFeedback>"
  "f555082d98a684b739b7f9ebba06a141")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'getposesFeedback)))
  "Returns md5sum for a message object of type 'getposesFeedback"
  "f555082d98a684b739b7f9ebba06a141")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<getposesFeedback>)))
  "Returns full string definition for message of type '<getposesFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define a feedback message~%bool poses_sent~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'getposesFeedback)))
  "Returns full string definition for message of type 'getposesFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define a feedback message~%bool poses_sent~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <getposesFeedback>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <getposesFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'getposesFeedback
    (cl:cons ':poses_sent (poses_sent msg))
))
